### ISSUE TITLE
KeyError: 'data'

### ISSUE THREAD

**Issue by lumuwu** [hacksman/spider_world#14]
Traceback (most recent call last):
  File "video_download_run.py", line 13, in <module>
    douyin_crawl = DouyinCrawl()
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 71, in __init__
    self.common_params = common_params(self)
  File "..\www_douyin_com\common\utils.py", line 75, in common_params
    device_info = getDevice(self)
  File "..\www_douyin_com\common\utils.py", line 44, in getDevice
    device_info = resp['data']
KeyError: 'data'

**Comment by KennyLiu25775** [comment]
same issue here too
