### ISSUE TITLE
抖音好像不能爬了

### ISSUE THREAD

**Issue by Praying** [hacksman/spider_world#17]
```
PS D:\SourceCode\douyin\spider_world\www_douyin_com> python .\video_download_run.py -upost 66076741938
Traceback (most recent call last):
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x036E0D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.appsign.vip', port=2688): Max retries exceeded with url: /douyin/device/new/version/2.7.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x036E0D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\video_download_run.py", line 13, in <module>
    douyin_crawl = DouyinCrawl()
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 69, in __init__
    self.common_params = common_params()
  File "..\www_douyin_com\common\utils.py", line 74, in common_params
    device_info = getDevice()
  File "..\www_douyin_com\common\utils.py", line 41, in getDevice
    resp = requests.get(API + "/douyin/device/new/version/2.7.0").json()
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\quran\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.appsign.vip', port=2688): Max retries exceeded with url: /douyin/device/new/version/2.7.0 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x036E0D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by undefined9999** [comment]
是我电脑坏了么....抖音不能爬了呀

**Comment by Praying** [comment]
@wuxin1210 应该是抖音那边做了变更，可能需要作者更新一下代码

**Comment by undefined9999** [comment]
> @ wuxin1210应该是抖音那边做了变更，可能需要作者更新一下代码

恩恩, 谢谢解答.  那得辛苦作者大佬辛苦一下

**Comment by KennyLiu25775** [comment]
都散了吧 Appsign 关闭了 以后谁也别想爬了

**Comment by lifeinearth** [comment]
是啊  Appsign 关闭了，完蛋
