### ISSUE TITLE
抖音爬虫无法使用

### ISSUE THREAD

**Issue by ssthe** [hacksman/spider_world#27]
```
python3 douyin_crawl.py
Traceback (most recent call last):
  File "douyin_crawl.py", line 342, in <module>
    douyin.grab_comment_main(aweme_id, 0)
  File "douyin_crawl.py", line 157, in grab_comment_main
    has_more = self.__grab_comment(aweme_id, upvote_bound)
  File "douyin_crawl.py", line 216, in __grab_comment
    hasmore = int(comment_content.get("hasmore"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
确认已经修改过Token和视频ID，查了一下很多项目都停止于今年五月，这个项目还在运作吗？

**Comment by junges521** [comment]
算法我修改了，可以联系我qq号1570207752
