### ISSUE TITLE
使用命令报错No module named 'backports'

### ISSUE THREAD

**Issue by cooper1x** [hacksman/spider_world#6]
```
python video_download_run.py -m -upost 58065297584
Traceback (most recent call last):
  File "video_download_run.py", line 11, in <module>
    from www_douyin_com.spiders.douyin_crawl import DouyinCrawl
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 4, in <module>
    from backports import csv
ModuleNotFoundError: No module named 'backports'
```

**Comment by cooper1x** [comment]
我是win10下的Python3.7

**Comment by Xuxudong166** [comment]
嗨，我也遇到相同的问题，通过把  from backports import csv  改为  import csv  问题就解决了，希望对你有用。

**Comment by cooper1x** [comment]
@Xuxudong166 请问是哪个文件的呢？

**Comment by Xuxudong166** [comment]
..\www_douyin_com\spiders\douyin_crawl.py  文件下，你的报错提示中有相应的位置的。

**Comment by cooper1x** [comment]
@Xuxudong166 改了出现新的报错
```
Traceback (most recent call last):
  File "video_download_run.py", line 11, in <module>
    from www_douyin_com.spiders.douyin_crawl import DouyinCrawl
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 7, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by Xuxudong166** [comment]
在命令行中使用 pip install requests 安装python的第三方库，类似问题可自行搜索解决
搜索办法：复制 ModuleNotFoundError: No module named 'requests'文本到百度或Google搜索框，点击搜索获取结果，希望对你有用。

**Comment by cooper1x** [comment]
pip安装了，然后下载了几个就这样
```
Traceback (most recent call last):
  File "video_download_run.py", line 34, in <module>
    douyin_crawl.grab_user_media(sys.argv[-1], "USER_POST", content='-m')
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 127, in grab_user_media
    hasmore, max_cursor = self.grab_video(user_id, action, content)
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 166, in grab_video
    self.download_user_video(aweme_id, **download_item)
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 233, in download_user_video
    video_content = self.download_video(aweme_id)
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 277, in download_video
    sign = getSign(self.__get_token(), query_params)
  File "..\www_douyin_com\common\utils.py", line 62, in getSign
    sign = resp['data']
KeyError: 'data'
```
另外问一下，下载的东西存哪去了呢？

**Comment by Xuxudong166** [comment]
我的存放在 D:\videos下

**Comment by cooper1x** [comment]
找到了，在`C:\videos\`下。
下载了几个视频是对的，没有水印，但是MP3都是1kb不可播放的……

**Comment by Xuxudong166** [comment]
是的，我的音频无法播放的，期待作者完善它。

**Comment by buptbf** [comment]
我的在Win10下，pycharm中运行video_download_run.py;出现了一下错误
Traceback (most recent call last):
  File "D:/spider_world/www_douyin_com/video_download_run.py", line 36, in <module>
    if sys.argv[1] == "-ulike":
IndexError: list index out of range

**Comment by buptbf** [comment]
在Pycharm Terminal 中运行 video_download_run.py 出现以下错误：
Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)

**Comment by UserHrsat** [comment]
> ```
> python video_download_run.py -m -upost 58065297584
> Traceback (most recent call last):
>   File "video_download_run.py", line 11, in <module>
>     from www_douyin_com.spiders.douyin_crawl import DouyinCrawl
>   File "..\www_douyin_com\spiders\douyin_crawl.py", line 4, in <module>
>     from backports import csv
> ModuleNotFoundError: No module named 'backports'
> ```

问题同上，通过from backports import csv改为import csv,问题解决；
但是为什么我扫出来的ID是六位数字和字母的组合？
然后就：
2018-11-29 21:31:44,886 - utils.py[line:104] INFO - 请输入正确的用户id， 用户id为10,11,12或13位纯数字...
Traceback (most recent call last):
  File "video_download_run.py", line 32, in <module>
    douyin_crawl.grab_user_media(sys.argv[-1], "USER_POST")
  File "../www_douyin_com/common/utils.py", line 105, in wrapper
    raise Exception
Exception

**Comment by liuyaming123** [comment]
> pip安装了，然后下载了几个就这样
> 
> ```
> Traceback (most recent call last):
>   File "video_download_run.py", line 34, in <module>
>     douyin_crawl.grab_user_media(sys.argv[-1], "USER_POST", content='-m')
>   File "..\www_douyin_com\spiders\douyin_crawl.py", line 127, in grab_user_media
>     hasmore, max_cursor = self.grab_video(user_id, action, content)
>   File "..\www_douyin_com\spiders\douyin_crawl.py", line 166, in grab_video
>     self.download_user_video(aweme_id, **download_item)
>   File "..\www_douyin_com\spiders\douyin_crawl.py", line 233, in download_user_video
>     video_content = self.download_video(aweme_id)
>   File "..\www_douyin_com\spiders\douyin_crawl.py", line 277, in download_video
>     sign = getSign(self.__get_token(), query_params)
>   File "..\www_douyin_com\common\utils.py", line 62, in getSign
>     sign = resp['data']
> KeyError: 'data'
> ```
> 我的也是这个问题，resp返回的是网络服务错误，自然data就不对

**Comment by liuyaming123** [comment]
作者，我想我们可以讨论下，微信：18321376139

**Comment by sqyaoyuan** [comment]
> ..\www_douyin_com\spiders\douyin_crawl.py 文件下，你的报错提示中有相应的位置的。
按照您说的改了成功了下载了，视频也是在C盘根目录下的，另外我看现在抖音分享的名片上域名前面加了iesdouyin.com

**Comment by sqyaoyuan** [comment]
File "video_download_run.py", line 32, in <module>
    douyin_crawl.grab_user_media(sys.argv[-1], "USER_POST")
  File "..\www_douyin_com\common\utils.py", line 106, in wrapper
    return func(self, *args, **kwargs)
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 112, in grab_user_media
    hasmore, max_cursor = self.grab_video(user_id, action, content)
  File "..\www_douyin_com\common\utils.py", line 106, in wrapper
    return func(self, *args, **kwargs)
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 152, in grab_video
    self.download_user_video(aweme_id, **download_item)
  File "..\www_douyin_com\spiders\douyin_crawl.py", line 238, in download_user_video
    with open("{}/videos/{}/{}.mp4".format(file_path_grandfather, author_nick_name, video_name), 'wb') as f:

ID没有问题但是一直显示这个。。。。/
