### ISSUE TITLE
运行中偶现Error，getSign  sign = resp['data']

### ISSUE THREAD

**Issue by haiblee** [hacksman/spider_world#7]
Traceback (most recent call last):
  File "video_download_run.py", line 32, in <module>
    douyin_crawl.grab_user_media(sys.argv[-1], "USER_POST")
  File "../www_douyin_com/spiders/douyin_crawl.py", line 127, in grab_user_media
    hasmore, max_cursor = self.grab_video(user_id, action, content)
  File "../www_douyin_com/spiders/douyin_crawl.py", line 166, in grab_video
    self.download_user_video(aweme_id, **download_item)
  File "../www_douyin_com/spiders/douyin_crawl.py", line 233, in download_user_video
    video_content = self.download_video(aweme_id)
  File "../www_douyin_com/spiders/douyin_crawl.py", line 277, in download_video
    sign = getSign(self.__get_token(), query_params)
  File "../www_douyin_com/common/utils.py", line 62, in getSign
    sign = resp['data']
KeyError: 'data'

**Comment by haiblee** [comment]
Traceback (most recent call last):
  File "video_download_run.py", line 32, in <module>
    douyin_crawl.grab_user_media(sys.argv[-1], "USER_POST")
  File "../www_douyin_com/spiders/douyin_crawl.py", line 127, in grab_user_media
    hasmore, max_cursor = self.grab_video(user_id, action, content)
  File "../www_douyin_com/spiders/douyin_crawl.py", line 166, in grab_video
    self.download_user_video(aweme_id, **download_item)
  File "../www_douyin_com/spiders/douyin_crawl.py", line 233, in download_user_video
    video_content = self.download_video(aweme_id)
  File "../www_douyin_com/spiders/douyin_crawl.py", line 291, in download_video
    play_addr_raw = resp_result['aweme_detail']['video']['play_addr']['url_list']
KeyError: 'video'
