### ISSUE TITLE
无法获得作者或作品ID

### ISSUE THREAD

**Issue by UserHrsat** [hacksman/spider_world#8]
为什么我扫出来的ID是六位数字和字母的组合？
然后就：
2018-11-29 21:31:44,886 - utils.py[line:104] INFO - 请输入正确的用户id， 用户id为10,11,12或13位纯数字...
Traceback (most recent call last):
File "video_download_run.py", line 32, in 
douyin_crawl.grab_user_media(sys.argv[-1], "USER_POST")
File "../www_douyin_com/common/utils.py", line 105, in wrapper
raise Exception
Exception

**Comment by UserHrsat** [comment]
问题以解决：
以链接分享作者或视频，使用chrome粘贴并转到，再次点击地址栏就会看到作者和视频的ID
